### ISSUE TITLE
SSB-37: PHP - Incorrect value is displayed for PackageHomePage for root package

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#100]
Original Reporter: nvelagapudi
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-37

spdx-sbom-generator tool version v0.0.2Test Repo that I used for testinghttps://github.com/woocommerce/woocommerceObserved that incorrect value is displayed for PackageHomePage for root packageSPDX data (PFA SPDX for reference)Package.json

**Comment by niruautomation** [comment]
Verified and closed in JIRA and hence closing the ticket
