### ISSUE TITLE
SSB-36: PHP - Version is not displayed for SPDXID even when versions exists for root package in package.json

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#101]
Original Reporter: nvelagapudi
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-36

spdx-sbom-generator tool version v0.0.2Test Repo that I used for testinghttps://github.com/woocommerce/woocommerceObserved that version is not displayed for SPDXID even when versions exists for root package in package.jsonSPDX data (PFA SPDX for reference)Package.json

**Comment by niruautomation** [comment]
As per comments in JIRA version is not needed and hence closing the ticket
