### ISSUE TITLE
SSB-35: PHP - Version is not displayed for DocumentName

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#102]
Original Reporter: nvelagapudi
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-35

spdx-sbom-generator tool version v0.0.2Test Repo that I used for testinghttps://github.com/woocommerce/woocommerceObserved that version is not displayed for DocumentName even when version exists in package.json. As per the spec https://confluence.linuxfoundation.org/display/PROD/PHP+-+Composer below is the description for field DocumentName${name}-${version}. The fields name and the version from the package.json will uniquely identify the document.SPDX data (PFA SPDX for reference)Package.json

**Comment by niruautomation** [comment]
Verified in JIRA
