### ISSUE TITLE
SSB-28: Go - Issues with the CopyrightText in SPDX file for github.com.coreos.go-systemd-v0.0.0-20190321100706-95778dfbb74e

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#109]
Original Reporter: nvelagapudi
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-28

spdx-sbom-generator tool version v0.0.2Test Repo that I used for testinghttps://github.com/spdx/spdx-sbom-generatorAs per the description in https://confluence.linuxfoundation.org/display/PROD/Golang+Mod we need to extract the text found starting with the keyword 'Copyright (c)' and until the newline. However text with just Copyright is extracted. SPDX data (PFA SPDX for reference)License data in github for V1.2.2https://github.com/coreos/go-systemd/blob/0/LICENSE

**Comment by niruautomation** [comment]
Verified and closed in JIRA and hence closing the ticket
