### ISSUE TITLE
SSB-26: Go - Issues with the CopyrightText in SPDX file for github.com.OneOfOne.xxhash-v1.2.2

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#111]
Original Reporter: nvelagapudi
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-26

spdx-sbom-generator tool version v0.0.2Test Repo that I used for testinghttps://github.com/spdx/spdx-sbom-generatorAs per the description in https://confluence.linuxfoundation.org/display/PROD/Golang+Mod we need to extract the text found starting with the keyword 'Copyright (c)' and until the newline. However text with just Copyright is extracted. Also in the license I validate there are many sentences with copyright and not sure how SPDX picked the text. I could not find the license in the downloaded dependencies and hence I validated in the githubNOTE Observed same issues for below packages as well github.com.coreos.pkg-v0.0.0-20180928190104-399ea9e2e55f github.com.flynn.go-shlex-v0.0.0-20150515145356-3f9db97f8568SPDX data (PFA SPDX for reference)License data in github for V1.2.2 [https://github.com/OneOfOne/xxhash/blob/v1.2.2/LICENSE ]*[https://github.com/OneOfOne/xxhash/blob/v1.2.2/LICENSE]*

**Comment by niruautomation** [comment]
Verified and closed in JIRA and hence closing the ticket
