### ISSUE TITLE
SSB-24: SBOM version does not show the actual tool version for Creator in generated SPDX file with SBOM binaries

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#113]
Original Reporter: nvelagapudi
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-24

Download spdx-sbom-genertor v0.0.2 from https://github.com/spdx/spdx-sbom-generator/releasesExecute ./spdx-sbom-generator to generate the SPDX file for the repositoryObserved that creator field has older version instead of v0.0.2

**Comment by niruautomation** [comment]
Verified and closed in JIRA and hence closing the ticket
