### ISSUE TITLE
SSB-6: Java (Maven)

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#120]
Original Reporter: vnaidu
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-6

**Comment by dealako** [comment]
This ticket a parent epic for all the Java/Maven tickets.

**Comment by dealako** [comment]
This is migrated epic ticket from JIRA. Closing this ticket in GH as we don't need it.
