### ISSUE TITLE
Java - Maven - PackageVersion field is not displayed and Version is not displayed for SPDXID for plugin when it is listed as package

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#130]
@prathapbproximabiz
**Tool Version** Cloned code from main branch of https://github.com/spdx/spdx-sbom-generator on 11-06-2021 and built the tool
**Test Repo** https://github.com/zxing/zxing
**OS** Windows 10

**_Issue1_** PackageVersion field is not displayed for plugin when it is listed as package
_**Issue2**_ Version is not displayed for SPDXID for plugin when it is listed as package

**_SPDX file_**
![image](https://user-images.githubusercontent.com/73597479/121640111-24c46080-caab-11eb-92e8-6dd9168c97df.png)

**_pom.xml_**
![image](https://user-images.githubusercontent.com/73597479/121640638-ce0b5680-caab-11eb-921b-6dcbc384e44d.png)

**Comment by prathapbproximabiz** [comment]
@niruautomation at room level pom.xml it has version and spdx file has version 
![image](https://user-images.githubusercontent.com/75629724/121642358-09a72000-caae-11eb-80b5-c455464ca55d.png)

The one which is not having version is from android module pom.xml file. It does not have version number 
![image](https://user-images.githubusercontent.com/75629724/121642137-bc2ab300-caad-11eb-8ceb-16cef481fce8.png)

**Comment by niruautomation** [comment]
@prathapbproximabiz 
Thank you for the clarification. Now I am able to understand the logic 
But are we supposed to skip the PackageVersion when version is missing

**Comment by prathapbproximabiz** [comment]
@niruautomation This is issue is fixed. Will be sending PR shortly.

**Comment by niruautomation** [comment]
Verified that the issue is fixed
[bom-Java-Maven.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6646895/bom-Java-Maven.spdx.txt)
