### ISSUE TITLE
Java - Maven - Versions are displayed for dependencies even when there are no versions for dependencies in pom.xml of the package

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#134]
@prathapbproximabiz
**Tool Version** Cloned code from main branch of https://github.com/spdx/spdx-sbom-generator on 11-06-2021 and built the tool
**Test Repo** https://github.com/zxing/zxing
**OS** Windows 10

Versions are displayed for dependencies even when there are no versions for dependencies in pom.xml of the package. Below is one of the example for Package-guava-30.1.1-android. They are not even in available in the output of mvn tree and mvn list commands
**SPDX File**
![image](https://user-images.githubusercontent.com/73597479/121649523-470fab80-cab6-11eb-9330-8298a15942e8.png)

**pom.xml for Package-guava-30.1.1-android**
![image](https://user-images.githubusercontent.com/73597479/121649574-54c53100-cab6-11eb-8473-ba1e9e4c6f2a.png)

**Comment by prathapbproximabiz** [comment]
The versions were indeed from mvn dependency tree.
![image](https://user-images.githubusercontent.com/75629724/121671115-cd82b800-cacb-11eb-90ad-f8e932b41b4b.png)

**Comment by niruautomation** [comment]
Verified that versions are fetched from mvn dependency:tree
![image](https://user-images.githubusercontent.com/73597479/121866368-7de6fb00-cd1c-11eb-8f56-37c31a51fe19.png)
