### ISSUE TITLE
Ruby - Issues with dependencies displayed for Relationship DEPENDS_ON

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#138]
**Tool Version** Cloned code from main branch of https://github.com/spdx/spdx-sbom-generator on 11-06-2021 and built the tool
**Test Repo** https://github.com/lewisojile/ruby-gem-sample
**OS** Windows 10

**_Issue1 - Relationship DEPENDS_ON not displayed even when Dependencies exists for package in gemspec_**
![image](https://user-images.githubusercontent.com/73597479/121663638-3fef9a00-cac4-11eb-9ec6-5e9e8913c96c.png)

![image](https://user-images.githubusercontent.com/73597479/121663762-5e559580-cac4-11eb-8ad1-6eb5763edcfd.png)

**_Issue2 - Few dependencies are not displayed for Relationship DEPENDS_ON_**
Dependency peck is missing in SPDX file
![image](https://user-images.githubusercontent.com/73597479/121664458-23a02d00-cac5-11eb-8ed3-5a70b023b568.png)

![image](https://user-images.githubusercontent.com/73597479/121665513-0455cf80-cac6-11eb-94cb-35fd9f53a7f7.png)

**Comment by lewisojile** [comment]
@niruautomation @niravpatel27 As observed in the gem plugin, a few dependencies such as 'hoe, peck & pry' have no metadata of any form in all gem locations in the local file system. This I verified by looking up all the gem paths displayed after running the 'gem env' command. Such dependencies were not included as we had no meta-data / gemspec files f or them.

**Comment by niruautomation** [comment]
I cloned the code from master on 14-06-2021, build the tool and verified the ticket. Observed that the issue is fixed
[bom-bundler.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6646614/bom-bundler.spdx.txt)
