### ISSUE TITLE
Python(Go) - poetry - https://None is displayed for PackageHomePage when there is no homepage value

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#144]
@lfpratik
**Tool Version** Cloned code from main branch of https://github.com/spdx/spdx-sbom-generator on 11-06-2021 and built the tool
**Test Repo** https://github.com/lfpratik/spdx-poetry-demo
**OS** Windows 10

1. Followed all prerequisite steps as per https://confluence.linuxfoundation.org/display/PROD/SPDX+-+Python+Module+-+Prerequisites+For+Windows
2. Followed Prerequisite and Steps as per below screenshot
![image](https://user-images.githubusercontent.com/73597479/121684233-0cb90500-cadc-11eb-88cb-d0be8a627ccf.png)
3. Execute ./spdx-sbom-generator
4. Observed that https://None is displayed for PackageHomePage when there is no homepage value
![image](https://user-images.githubusercontent.com/73597479/121684279-1e021180-cadc-11eb-9a91-dbf987e7a0dd.png)

![image](https://user-images.githubusercontent.com/73597479/121684484-5dc8f900-cadc-11eb-98ca-1d225433dd6f.png)

**Comment by lfpratik** [comment]
@niruautomation, The newly rolled out version will have a fix for this issue.

cc: @niravpatel27 and @licquia

**Comment by niruautomation** [comment]
I cloned the code from master on 14-06-2021, build the tool and verified the ticket.
Observed that NOASSERTION is displayed
![image](https://user-images.githubusercontent.com/73597479/121876289-f8b51380-cd26-11eb-9684-798b424ba05d.png)
