### ISSUE TITLE
Python(Go) - pipenv/venv - Details of Document and root package are not matching with the repo against which SPDX file is generated

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#156]
@lfpratik 
**Tool Version** I cloned the code from master on 14-06-2021, build the tool and verified the ticket
**Test Repo** https://github.com/lfpratik/spdx-pipenv-demo
**OS** Windows 10

1. Followed all prerequisite steps as per https://confluence.linuxfoundation.org/display/PROD/SPDX+-+Python+Module+-+Prerequisites+For+Windows
2. Followed Prerequisite and Steps as per below screenshot
![image](https://user-images.githubusercontent.com/73597479/121533821-462b3b00-ca1e-11eb-8868-09f28bed00a6.png)
3. Execute ./spdx-sbom-generator
4. Observed that SPDX file is generated but details of Document and root package are not matching with the repo against which SPDX file is generated

![image](https://user-images.githubusercontent.com/73597479/121871671-ff8d5780-cd21-11eb-99e3-ecfac9947df6.png)

![image](https://user-images.githubusercontent.com/73597479/121871729-0f0ca080-cd22-11eb-9ba6-7eb0e5ecdc7c.png)

**Comment by lfpratik** [comment]
@niruautomation, the following output, is expected. This is generated on Linux Machine. I will take a look of the windows issue.

`SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: spdx-pipenv-demo-0.0.1
DocumentNamespace: http://spdx.org/spdxpackages/spdx-pipenv-demo-0.0.1-649d8602-227d-4afe-a07f-20ddfdece7b7
Creator: Tool: spdx-sbom-generator-0.0.1
Created: 2021-06-14T10:59:24Z

##### Package representing the spdx-pipenv-demo

PackageName: spdx-pipenv-demo
SPDXID: SPDXRef-Package-spdx-pipenv-demo
PackageVersion: 0.0.1
PackageSupplier: NOASSERTION
PackageDownloadLocation: NOASSERTION
FilesAnalyzed: false
PackageChecksum: SHA1: 3bd71887b1244298ae19ca516df14f39061c668d
PackageHomePage: https://github.com/lfpratik/spdx-pipenv-demo
PackageLicenseConcluded: NOASSERTION
PackageLicenseDeclared: NOASSERTION
PackageCopyrightText: NOASSERTION
PackageLicenseComments: NOASSERTION
PackageComment: NOASSERTION
`

**Comment by niruautomation** [comment]
@lfpratik As discussed the issue is observed with SPDX file generated for venv as well

**Comment by niruautomation** [comment]
Verified that the issue is fixed
[bom-pyenv.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6713735/bom-pyenv.spdx.txt)
[bom-pipenv.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6713738/bom-pipenv.spdx.txt)
