### ISSUE TITLE
Missing ':' after 'Relationship' tags

### ISSUE THREAD

**Issue by swinslow** [spdx/spdx-sbom-generator#161]
## Summary

When running spdx-sbom-generator on itself, the resulting SBOM is missing the colon (':') after each 'Relationship' tag.

## Background

1. cloned main branch (a795777) and built for Linux Intel/AMD 64-bit version
2. ran spdx-sbom-generator on its own directory

## Expected behavior

Every "Relationship" tag should be followed by a colon (':') like other tags, but they are not.

## Screenshots

![missing-colons](https://user-images.githubusercontent.com/678569/122787298-319f3c00-d283-11eb-8542-cf47c666f9a5.png)

**Comment by niravpatel27** [comment]
@swinslow FYI https://github.com/spdx/spdx-sbom-generator/pull/163

**Comment by kestewart** [comment]
Looks like this has been resolved, so closing this and removing from the tracking.   @swinslow - please reopen if this is not the case.

**Comment by swinslow** [comment]
Thanks! I haven't re-run tests but this looks like it should have fixed it.
