### ISSUE TITLE
.NET - Value for PackageDownloadLocation is displayed as NOASSERTION even when value exists for {package.repository.url}

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#173]
@proximapc 
**Tool Version** v0.0.8
**Test Repo** https://github.com/jasontaylordev/CleanArchitecture
**OS** Windows 10

Observed that value for PackageDownloadLocation is displayed as NOASSERTION even when value exists for {package.repository.url}. As per specification file {package.repository.url should be displayed for PackageDownloadLocation

**Specification file**
![image](https://user-images.githubusercontent.com/73597479/123532323-dd380880-d729-11eb-83df-c5396f9322bb.png)

**Example1 Package-FluentValidation-9.3.0**
![image](https://user-images.githubusercontent.com/73597479/123532274-76b2ea80-d729-11eb-85c0-0904637b5d0f.png)

![image](https://user-images.githubusercontent.com/73597479/123532295-a3ff9880-d729-11eb-86e2-88ed92dfc530.png)

**Example2 Package-MediatR-9.0.0**
![image](https://user-images.githubusercontent.com/73597479/123532341-0e183d80-d72a-11eb-806c-15372de97dfb.png)

![image](https://user-images.githubusercontent.com/73597479/123532352-24be9480-d72a-11eb-98fd-56c3aec0349b.png)

**Example3 Package-AutoMapper-10.0.0**
![image](https://user-images.githubusercontent.com/73597479/123532391-69e2c680-d72a-11eb-92b3-9498d829ffd8.png)

![image](https://user-images.githubusercontent.com/73597479/123532416-867efe80-d72a-11eb-8730-12c92065556f.png)

**Comment by proximapc** [comment]
@niruautomation I am not sure about this url but still, I have added the support. Once the PR gets merged you can verify it. 
We have different URLs for the package download. Please check the link for the Automapper package https://www.nuget.org/packages/AutoMapper/ on the right-hand side menu panel, we see the download package link. This URL is not present in the nuspec file.

**Comment by niruautomation** [comment]
@proximapc 
Observed that NOASSERTION is displayed for PackageDownloadLocation. As per clarification provided by Nirav, NOASSERTION should not be displayed
![image](https://user-images.githubusercontent.com/73597479/123604201-40a06400-d818-11eb-822c-e4e376f6afa5.png)

![image](https://user-images.githubusercontent.com/73597479/123603951-02a34000-d818-11eb-98fa-fdaddb0d79d9.png)

**Comment by proximapc** [comment]
@niruautomation please verify this issue once the PR gets merged

**Comment by niruautomation** [comment]
Verified with version v0.0.10 and observed that the issue is fixed
[bom-nuget_eShopOnWeb_v0.0.10_30-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6740768/bom-nuget_eShopOnWeb_v0.0.10_30-Jun-2021.spdx.txt)
