### ISSUE TITLE
Java - Maven - NOASSERTION is displayed for both PackageSupplier and PackageDownloadLocation even when values exists as per the conditions mentioned in specification

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#175]
@prathapbproximabiz
**Tool Version** Tested with v.0.0.8 and as well as tested with binaries built from cloned code from main branch of https://github.com/spdx/spdx-sbom-generator on 27-06-2021
**Test Repo** https://github.com/mybatis/mybatis-3
**OS** Windows 10

Observed that NOASSERTION is displayed for both PackageSupplier and PackageDownloadLocation for all packages even when values exists as per the conditions mentioned in specification
**SPDX files**
[bom-Java-Maven_generated with Latest code.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721053/bom-Java-Maven_generated.with.Latest.code.spdx.txt)
[bom-Java-Maven_mybatis-3_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721054/bom-Java-Maven_mybatis-3_v0.0.8_27-Jun-2021.spdx.txt)
[bom-Java-Maven_sample-java-programs_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721055/bom-Java-Maven_sample-java-programs_v0.0.8_27-Jun-2021.spdx.txt)
[bom-Java-Maven_zxing_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721056/bom-Java-Maven_zxing_v0.0.8_27-Jun-2021.spdx.txt)

**Specification**
![image](https://user-images.githubusercontent.com/73597479/123533418-0b6e1600-d733-11eb-8c20-d4f8c24e4b49.png)

**Example**
![image](https://user-images.githubusercontent.com/73597479/123533472-a4049600-d733-11eb-9742-3e5c5a2e475a.png)

![image](https://user-images.githubusercontent.com/73597479/123533467-90f1c600-d733-11eb-8dec-d932a4806bc2.png)

**Comment by prathapbproximabiz** [comment]
@niruautomation To set PackageDownloadLocation value, you should have value for <downloadUrl> tag under <distributionManagement> tag.

**Comment by niruautomation** [comment]
@prathapbproximabiz 
https://github.com/zxing/zxing
**packageSupplier**
Developer tag is not a subtag in in the pm file. I am providing another example here. I have attached SPDX files for 3 repos and in none of the the value is populated for packageSupplier
![image](https://user-images.githubusercontent.com/73597479/123545013-a1299580-d773-11eb-9f13-8f0db4a8a3f9.png)

**PackageDownloadLocation**
As per sepc downloadurl exists under distributionManagement but NOASSERTION is displayed in the SPDX file. I have attached SPDX files for 3 repos and in none of the the value is populated for packageSupplier
![image](https://user-images.githubusercontent.com/73597479/123545654-bce26b00-d776-11eb-80d2-e98bc7b9642c.png)

**Comment by prathapbproximabiz** [comment]
@mlehotskylf  @niruautomation Hi Nirupama, i am able to get both PackageSupplier and PackageDownloadLocation.
Could you please retest and let me know if you need any help.

![image](https://user-images.githubusercontent.com/75629724/123573579-da9de780-d7eb-11eb-8118-2a142da8b836.png)

**Comment by niruautomation** [comment]
@prathapbproximabiz 
I cloned the code from main bran and built the SBOM generator and I am still able to reproduce the issue. Not sure if is windows specific issue. Also as per below confirmation from @niravpatel27 NOASSERTION should not be displayed for the fields
[bom-Java-Maven_mybatis-3_28-Jun-2021.txt](https://github.com/spdx/spdx-sbom-generator/files/6723488/bom-Java-Maven_mybatis-3_28-Jun-2021.txt)
[bom-Java-Maven_sample-java-programs_28-Jun-2021.txt](https://github.com/spdx/spdx-sbom-generator/files/6723490/bom-Java-Maven_sample-java-programs_28-Jun-2021.txt)
[bom-Java-Maven_zxing_28-Jun-2021.txt](https://github.com/spdx/spdx-sbom-generator/files/6723492/bom-Java-Maven_zxing_28-Jun-2021.txt)

![image](https://user-images.githubusercontent.com/73597479/123581728-1cce2580-d7fa-11eb-855b-be2ace71b7b2.png)

**Comment by prathapbproximabiz** [comment]
@mlehotskylf @niruautomation Cloned the code from spdx main branch and build SBOM generator. I am able to set values for both fields.
![image](https://user-images.githubusercontent.com/75629724/123590559-6b82bc00-d808-11eb-95d4-78e210dd2e2d.png)

**Comment by niruautomation** [comment]
@prathapbproximabiz 
I am testing in windows OS. Could this be a windows issue?

**Comment by prathapbproximabiz** [comment]
https://github.com/spdx/spdx-sbom-generator/pull/192

**Comment by niruautomation** [comment]
Verified with version v0.0.10 and observed that the issue is fixed
[bom-Java-Maven_mybatis-3_v0.0.10_30-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6740752/bom-Java-Maven_mybatis-3_v0.0.10_30-Jun-2021.spdx.txt)
[bom-Java-Maven_sample-java-programs_v0.0.10_30-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6740753/bom-Java-Maven_sample-java-programs_v0.0.10_30-Jun-2021.spdx.txt)
[bom-Java-Maven_zxing_v0.0.10_30-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6740754/bom-Java-Maven_zxing_v0.0.10_30-Jun-2021.spdx.txt)
