### ISSUE TITLE
Node- Yarn/NPM - NOASSERTION is displayed for PackageDownloadLocation even when values exists as per the conditions mentioned in specification

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#176]
@khalifapro
**Tool Version** v0.0.8
**Test Repo** https://github.com/gothinkster/node-express-realworld-example-app
**OS** Windows 10

Observed that NOASSERTION is displayed for PackageDownloadLocation even when values exists as per the conditions mentioned in specification

**SPDX file**
[bom-yarn_node-express-realworld-example-app_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721093/bom-yarn_node-express-realworld-example-app_v0.0.8_27-Jun-2021.spdx.txt)
[bom-yarn_typed-install_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721095/bom-yarn_typed-install_v0.0.8_27-Jun-2021.spdx.txt)
[bom-yarn_bolt_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721097/bom-yarn_bolt_v0.0.8_27-Jun-2021.spdx.txt)
[bom-npm_node-red_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721098/bom-npm_node-red_v0.0.8_27-Jun-2021.spdx.txt)

**Specification**
![image](https://user-images.githubusercontent.com/73597479/123534141-97367100-d738-11eb-9336-0b312de1547b.png)

**Issue**
![image](https://user-images.githubusercontent.com/73597479/123534179-d369d180-d738-11eb-921c-52400d8663d7.png)

![image](https://user-images.githubusercontent.com/73597479/123534191-e41a4780-d738-11eb-9e7e-1952082effe0.png)

**Comment by khalifapro** [comment]
we have two types of dependancies,
1-direct dependency : which have resolved field in lock file.
2-dependency of dependency: package name and version only available in lock file.
ex: 
JSONStream v1.3.1 is a direct dependency so we can get PackageDownloadLocation
JSONStream v1.0.3. is dependency of dependency so we can not get PackageDownloadLocation

<img width="761" alt="spdx-downloadlocation-dependancies" src="https://user-images.githubusercontent.com/81648906/124002232-c6b5d980-d9d5-11eb-8be8-56688c753a0a.png">

<img width="743" alt="spdx-downloadloc" src="https://user-images.githubusercontent.com/81648906/124002231-c61d4300-d9d5-11eb-85b9-798fd3144e05.png">
<img width="837" alt="node-express-realworld-example-app – yarn lock 2021-06-30 18-53-34" src="https://user-images.githubusercontent.com/81648906/124002226-c4ec1600-d9d5-11eb-8473-2b31b3ee9282.png">

<img width="841" alt="node-express-realworld-example-app – yarn lock 2021-06-30 18-52-41" src="https://user-images.githubusercontent.com/81648906/124002221-c289bc00-d9d5-11eb-8670-b054f1e89e28.png">

**Comment by niruautomation** [comment]
@khalifapro 
As per the logic explained by Nirav, NOASSERTION should not be displayed for the fields
![image](https://user-images.githubusercontent.com/73597479/124056393-48901c00-da43-11eb-90ff-7d9c56cd8bac.png)

**Comment by niruautomation** [comment]
Cloned code from main branch, built the tool and verified that the issue is fixed
