### ISSUE TITLE
Ruby - NOASSERTION is displayed for PackageDownloadLocation even when values exists as per the conditions mentioned in specification

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#178]
**Tool Version** v.0.0.8
**Test Repo** https://github.com/lewisojile/ruby-gem-sample
**OS** Windows 10

Observed that NOASSERTION is displayed for PackageDownloadLocation even when values exists as per the conditions mentioned in specification

**Specification**
![image](https://user-images.githubusercontent.com/73597479/123536422-da4c1080-d747-11eb-943f-4332d6e2e91c.png)

**Issue**
[bom-bundler_ruby-gem-sample_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721204/bom-bundler_ruby-gem-sample_v0.0.8_27-Jun-2021.spdx.txt)
![image](https://user-images.githubusercontent.com/73597479/123536439-f0f26780-d747-11eb-9f56-0cb691a32ef8.png)

**Gemspec File**
![image](https://user-images.githubusercontent.com/73597479/123536465-0ff0f980-d748-11eb-97b1-29893c215edd.png)

**Comment by lewisojile** [comment]
Fixed. PR : https://github.com/spdx/spdx-sbom-generator/pull/186

**Comment by niruautomation** [comment]
Verified with version v0.0.10 and observed that the issue is fixed
[bom-bundler_ruby-gem-sample_v0.0.10_30-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6740572/bom-bundler_ruby-gem-sample_v0.0.10_30-Jun-2021.spdx.txt)
