### ISSUE TITLE
Ruby - There is no space between first name and last name and also double quotes are displayed for name for PackageSupplier

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#179]
**Tool Version** v.0.0.8
**Test Repo** https://github.com/lewisojile/ruby-gem-sample
**OS** Windows 10

Observed that there is no space between first name and last name and also double quotes are displayed for name
[bom-bundler_ruby-gem-sample_v0.0.8_27-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6721211/bom-bundler_ruby-gem-sample_v0.0.8_27-Jun-2021.spdx.txt)
![image](https://user-images.githubusercontent.com/73597479/123536672-69a5f380-d749-11eb-883f-ce9cd5d532bd.png)

![image](https://user-images.githubusercontent.com/73597479/123536683-7b879680-d749-11eb-8ae6-6a922887c1ae.png)

**Comment by lewisojile** [comment]
Fixed.PR: https://github.com/spdx/spdx-sbom-generator/pull/186

**Comment by niruautomation** [comment]
Verified with v0.0.10 tool and observed that the issue is fixed
![image](https://user-images.githubusercontent.com/73597479/123954580-3328dc80-d9c6-11eb-808c-dc32ce3ff910.png)
