### ISSUE TITLE
Rust - NOASSERTION is displayed for PackageDownloadLocation for root package

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#180]
@luismoriguerra 
**Tool Version** v0.0.8
**Test Repo** https://github.com/rust-random/rand
**OS** Windows 10

Observed that NOASSERTION is displayed for PackageDownloadLocation for root package

![image](https://user-images.githubusercontent.com/73597479/123537285-3e70d380-d74c-11eb-8399-70f27010e38f.png)

**Comment by luismoriguerra** [comment]
fix  https://github.com/spdx/spdx-sbom-generator/pull/190

**Comment by niruautomation** [comment]
Verified with v0.0.10 and observed that the issue is fixed
[bom-cargo_rand_v0.0.10_30-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6740522/bom-cargo_rand_v0.0.10_30-Jun-2021.spdx.txt)
