### ISSUE TITLE
.NET - NOASSERTION is displayed for PackageSupplier

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#188]
@proximapc 
**Tool Version** Cloned code from main branch on 28-06-2021 and built the tool
**OS** Windows 10

Observed that NOASSERTION is displayed for PackageSupplier. As per clarification provided by Nirav, NOASSERTION should not be displayed for the field

![image](https://user-images.githubusercontent.com/73597479/123604295-56158e00-d818-11eb-8cea-3893041b3afc.png)

![image](https://user-images.githubusercontent.com/73597479/123604761-c4f2e700-d818-11eb-8548-07210cf7df44.png)

![image](https://user-images.githubusercontent.com/73597479/123604827-d50ac680-d818-11eb-955d-d2bdc2c4239d.png)

**Comment by proximapc** [comment]
@niruautomation please verify once PR gets merged

**Comment by niruautomation** [comment]
Verified with v0.0.10 tool and observed that the issue is fixed
![image](https://user-images.githubusercontent.com/73597479/123948436-06bd9200-d9bf-11eb-8ca0-0e72945aa0f0.png)
