### ISSUE TITLE
Java - Maven - Warning message is displayed when SPDX file validated in the SPDX validator

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#29]
**Test Repo used for testing** https://github.com/mlehotskylf/sample-java-programs
1. Clone the https://github.com/spdx/spdx-sbom-generator.git from main branch (Since latest version tool is not available followed this approach for testing)
2. Execute the **make build-win** to build the tool
3. Generate the SPDX file for JAVA module
4. Validate the generated SPDX file in https://tools.spdx.org/app/validate/
5. Observed that the warning message is displayed. PFA SPDX file for reference
![image](https://user-images.githubusercontent.com/73597479/121307675-dd5c9980-c91d-11eb-9028-2fe1b2ca65b2.png)

[bom-Java-Maven.txt](https://github.com/spdx/spdx-sbom-generator/files/6621683/bom-Java-Maven.txt)

**Comment by prathapbproximabiz** [comment]
@niruautomation  Could you please retest it as discussed in our call.

**Comment by niruautomation** [comment]
Verified with latest version(v0.0.5) of the tool and observed that the issue is fixed
![image](https://user-images.githubusercontent.com/73597479/121403525-9e0f6680-c978-11eb-9d28-a37108a5ecb6.png)

**Comment by niruautomation** [comment]
@prathapbproximabiz
Observed this issue again. This seems to be an intermittent issue. Because if I generate the SPDX file again the it is not reproducible

**Tool Version** Cloned code from main branch of https://github.com/spdx/spdx-sbom-generator on 11-06-2021 and built the tool
**Test Repo** https://github.com/mybatis/mybatis-3
**OS** Windows 10

**_PFA files_**
[bom-javen-maven_withIssues.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6636876/bom-javen-maven_withIssues.spdx.txt)
[bom-javen-maven-withoutIssues.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6636877/bom-javen-maven-withoutIssues.spdx.txt)

**_Warning in SPDX validator_**
![image](https://user-images.githubusercontent.com/73597479/121655171-074bc280-cabc-11eb-8625-1442aebd1a2d.png)

**Comment by prathapbproximabiz** [comment]
![image](https://user-images.githubusercontent.com/75629724/121704751-a939d200-caf1-11eb-843b-e55dad130c9e.png)

@niruautomation  Please take latest code once below PR is approved and merged. And retest it.
https://github.com/spdx/spdx-sbom-generator/pull/143

**Comment by niruautomation** [comment]
This is an intermittent issue. Not able to reproduce the issue now
