### ISSUE TITLE
Java - Maven - Parent project version is displayed instead of module version for Package Version

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#32]
**Repo used for testing** https://github.com/mlehotskylf/sample-java-programs

Observed that Parent project version is displayed instead of module version for Package Version.
For e.g. highcpu-0.0.2-SNAPSHOT, Module version is 4.0.0. and parent project version is 0.0.2-SNAPSHOT

**SPDX file (PFA file for reference)**
[bom-Java-Maven.txt](https://github.com/spdx/spdx-sbom-generator/files/6623047/bom-Java-Maven.txt)
![image](https://user-images.githubusercontent.com/73597479/121339201-de9cbf00-c93b-11eb-8e90-3ffe2ed22a55.png)

**POM**
![image](https://user-images.githubusercontent.com/73597479/121339160-d2186680-c93b-11eb-8732-a734a2972cf1.png)

**Comment by niruautomation** [comment]
As discussed with @prathapbproximabiz this is expected behavior as the modules do not have version on pom.xml. However I will test more with other repositories and then either close/reopen the ticket

**Comment by prathapbproximabiz** [comment]
@niruautomation Modules can have version, with <version> tag. The <modelVersion> is not the module version.

**Comment by niruautomation** [comment]
Tested with other repos and verified below use cases
1. When module has version in pom.xml with tag version then module version is displayed
2. When module does not have version in pom.xml with tag version then version of root project is displayed for module
