### ISSUE TITLE
Rust - SPDX file validation failed in the SPDX validator

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#47]
@niravpatel27 
**Tool Version** v0.0.6
**Test Repo** https://github.com/rust-random/rand
**OS** Windows 10

Validate the SPDX file generated for rust in https://tools.spdx.org/app/validate/
Observed that the validation failed

SPDX file
[bom-cargo.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6628494/bom-cargo.spdx.txt)

![image](https://user-images.githubusercontent.com/73597479/121468127-ee69e100-c9d7-11eb-92f3-8bb43a60c3fe.png)

**Comment by luismoriguerra** [comment]
hi @niruautomation , looks this is already fixed , could you try with the last vesion of spdx binary 
this is one file I just generated today
[bom-cargo.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6633040/bom-cargo.spdx.txt)

**Comment by niruautomation** [comment]
Cloned the latest code and build the tool.
Verified and observed that the issue is fixed
![image](https://user-images.githubusercontent.com/73597479/121690768-e303dc00-cae3-11eb-89ce-2a30926ad10d.png)
