### ISSUE TITLE
.net - Warning message is displayed when SPDX file validated in the SPDX validator

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#48]
@proximapc 
**Tool Version** v0.0.6
**Test Repo** https://github.com/dotnet-architecture/eShopOnWeb
**OS** Windows 10

1. Clone the repo
2. Generate the SPDX file with command ./spdx-sbom-generator
![image](https://user-images.githubusercontent.com/73597479/121471560-88805800-c9dd-11eb-9c6d-c88d0d7d3b76.png)

Validate the SPDX file generated for rust in https://tools.spdx.org/app/validate/
Observed that warnings are displayed
**SPDX File**
[bom-nuget.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6628665/bom-nuget.spdx.txt)

![image](https://user-images.githubusercontent.com/73597479/121471217-ea8c8d80-c9dc-11eb-9e78-7d1491cf34b1.png)

**Comment by proximapc** [comment]
@niruautomation This is fixed, please verify using the latest code.

**Comment by niruautomation** [comment]
Verified that the issue is fixed
![image](https://user-images.githubusercontent.com/73597479/121714302-549b5480-cafb-11eb-9b56-27a93cd8e97e.png)

**Comment by niruautomation** [comment]
Observed this issue again with latest code
1. https://github.com/dotnet-architecture/eShopOnWeb
[bom-nuget_eShopOnWeb_25-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6715468/bom-nuget_eShopOnWeb_25-Jun-2021.spdx.txt)
2. https://github.com/jasontaylordev/CleanArchitecture
[bom-nuget_CleanArchitecture_25-Jun-2021.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6715470/bom-nuget_CleanArchitecture_25-Jun-2021.spdx.txt)

**Comment by proximapc** [comment]
@niruautomation please verify once the PR gets merged

**Comment by niruautomation** [comment]
Verified that the issue is fixed
![image](https://user-images.githubusercontent.com/73597479/123532528-66037400-d72b-11eb-9a50-1218643373ae.png)
