### ISSUE TITLE
Rust - Only name is displayed for Packagename for all but as per Spec both name and version should be displayed

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#49]
@niravpatel27
**Tool Version** v0.0.6
**Test Repo** https://github.com/rust-random/rand
**OS** Windows 10

Observed that only name is displayed for Packagename for root package but as per Spec both name and version should be displayed. Observed same issue when data is fetched from both Cargo.toml and cargo.lock

**Spec**
https://confluence.linuxfoundation.org/display/PROD/Rust+-+Cargo
![image](https://user-images.githubusercontent.com/73597479/121478687-e9f8f480-c9e6-11eb-9be5-97e4d05611b5.png)

**SPDX file**
![image](https://user-images.githubusercontent.com/73597479/121478801-06952c80-c9e7-11eb-826a-c7439b7a6c03.png)

**Cargo.toml**
![image](https://user-images.githubusercontent.com/73597479/121479087-4eb44f00-c9e7-11eb-85a0-4de72da5b73a.png)

**Comment by luismoriguerra** [comment]
@niruautomation 
the issue is the documentation which is not up-to-date .
I've already update that PackageName section 
![image](https://user-images.githubusercontent.com/3759580/121564997-a8197f80-c9e1-11eb-8f4d-45f7e30936c7.png)

**Comment by niruautomation** [comment]
As per above comment the documentation is updated and the current behavior is as expected and hence closing the ticket
