### ISSUE TITLE
.NET - https is displayed twice for PackageHomePage

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#54]
@proximapc
**Tool Version** v0.0.6
**Test Repo** https://github.com/dotnet-architecture/eShopOnWeb
**OS** Windows 10

Observed that https is displayed twice for PackageHomePage
![image](https://user-images.githubusercontent.com/73597479/121520037-0d846500-ca10-11eb-91f1-3524e4caf569.png)

**Comment by proximapc** [comment]
@niruautomation This is fixed, please verify using the latest code.

**Comment by niruautomation** [comment]
@proximapc 
I cloned from master branch and built the tool and tested the ticket.
Observed that the issue is still reproducible
![image](https://user-images.githubusercontent.com/73597479/121713611-b0b1a900-cafa-11eb-9b2e-c63757dd868b.png)
