### ISSUE TITLE
.NET - Data for PackageCopyrightText is displayed even when there is no data for PackageLicenseConcluded/PackageLicenseDeclared

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#57]
@proximapc
**Tool Version** v0.0.6
**Test Repo** https://github.com/dotnet-architecture/eShopOnWeb
**OS** Windows 10

Observed that data for PackageCopyrightText is displayed even when there is no data for PackageLicenseConcluded/PackageLicenseDeclared
![image](https://user-images.githubusercontent.com/73597479/121523274-a8327300-ca13-11eb-8a01-2c4287aaa66e.png)

**Comment by proximapc** [comment]
@niruautomation we get the Copyright text from the nuspec file, if it is present then we show it
![Screenshot from 2021-06-11 12-44-26](https://user-images.githubusercontent.com/52558975/121646364-ddda6900-cab2-11eb-9244-0cbb08a9ea6b.png)

**Comment by niruautomation** [comment]
As mentioned in above text from copyright tag is displayed for PackageCopyrightText. Closing the ticket
