### ISSUE TITLE
.NET - Incorrect data id displayed for PackageCopyrightText

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#58]
@proximapc
**Tool Version** v0.0.6
**Test Repo** https://github.com/dotnet-architecture/eShopOnWeb
**OS** Windows 10

Observed that incorrect data id displayed for PackageCopyrightText. Copyright text that does not exist in the license file is dsiplayed
**SPDX file**
![image](https://user-images.githubusercontent.com/73597479/121524200-ae751f00-ca14-11eb-9ec1-ae7ab10be690.png)

NUSPEC (Also observed that there is no license file in the folder)
![image](https://user-images.githubusercontent.com/73597479/121524287-c9e02a00-ca14-11eb-9b2f-561b81291754.png)

**License file**
https://licenses.nuget.org/Apache-2.0
![image](https://user-images.githubusercontent.com/73597479/121524399-e714f880-ca14-11eb-8387-c8fe29754068.png)

**Comment by proximapc** [comment]
@niruautomation I can see the copyright text in the fluentvalidation.nuspec v-9.3.0 at the bottommost, we are using the same text in the spdx file.  Please verify
![Screenshot from 2021-06-11 12-34-57](https://user-images.githubusercontent.com/52558975/121645770-34937300-cab2-11eb-8705-2afa5695b054.png)

**Comment by niruautomation** [comment]
As mentioned in above text from copyright tag is displayed for PackageCopyrightText. Closing the ticket
