### ISSUE TITLE
Python(Go) - Poetry - SPDX file validation failed in the SPDX validator

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#61]
@lfpratik
**Tool Version** v0.0.6
**Test Repo** https://github.com/lfpratik/spdx-pipenv-demo
**OS** Windows 10

Observed that the Python(Go) - Poetry  SPDX file validation failed in the SPDX validator. PFA SPDX file for reference
[bom-pip.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6631900/bom-pip.spdx.txt)

![image](https://user-images.githubusercontent.com/73597479/121536158-71168e80-ca20-11eb-89a3-577a1a12bc51.png)

**Comment by lfpratik** [comment]
@niruautomation, The newly rolled out version will have a fix for this issue.

cc: @niravpatel27 and @licquia

**Comment by niruautomation** [comment]
Verified that the issue is fixed
![image](https://user-images.githubusercontent.com/73597479/123374432-bd2b0c80-d5a4-11eb-9674-f2b9755a1d9c.png)
