### ISSUE TITLE
Python(Go) - venv - Not able to generate SPDX file

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#62]
@lfpratik
**Tool Version** v0.0.6
**Test Repo** https://github.com/lfpratik/spdx-venv-demo
**OS** Windows 10

1. Followed all prerequisite steps as per https://confluence.linuxfoundation.org/display/PROD/SPDX+-+Python+Module+-+Prerequisites+For+Windows
2. Followed Prerequisite and Steps as per below screenshot
![image](https://user-images.githubusercontent.com/73597479/121539718-86d98300-ca23-11eb-96bb-dcbee472187d.png)

3. Execute ./spdx-sbom-generator
4. Observed that SPDX file is not generated and below error is displayed
```
ASUS@LAPTOP-2QB11PTS MINGW64 /d/LFX/Projects/SPDX/Python/Go/spdx-venv-demo (main)
$ .venv/Scripts/pip freeze
click==8.0.1
colorama==0.4.4
iso8601==0.1.14
markdown==3.3.4
-e git+https://github.com/lfpratik/spdx-venv-demo.git@3f4ba9c3068fea4de71404022317ea980d3ce63b#egg=spdx_venv_demo

ASUS@LAPTOP-2QB11PTS MINGW64 /d/LFX/Projects/SPDX/Python/Go/spdx-venv-demo (main)
$ ./spdx-sbom-generator
INFO[2021-06-10T19:37:06+05:30] Starting to generate SPDX ...
INFO[2021-06-10T19:37:06+05:30] Running generator for Module Manager: `pip` with output `bom-pip.spdx`
INFO[2021-06-10T19:37:06+05:30] Command has completed with errors for some package managers, see details below
INFO[2021-06-10T19:37:06+05:30] Plugin pip return error Python version not found
```

**Comment by lfpratik** [comment]
@niruautomation, The newly rolled out version will have a fix for this issue.

cc: @niravpatel27 and @licquia

**Comment by niruautomation** [comment]
Verified that the issue is fixed
[bom-pyenv.spdx.txt](https://github.com/spdx/spdx-sbom-generator/files/6713750/bom-pyenv.spdx.txt)
![image](https://user-images.githubusercontent.com/73597479/123374552-e9468d80-d5a4-11eb-9f72-7cd6b8b1f577.png)
