### ISSUE TITLE
Node - Yarn - SPDX file not generated with for one of the repo

### ISSUE THREAD

**Issue by niruautomation** [spdx/spdx-sbom-generator#72]
@khalifapro
**Tool Version** v0.0.6
**Test Repo** https://github.com/nodejs/corepack
**OS** Windows 10

Observed that SPDX file is not generated and below error is displayed
![image](https://user-images.githubusercontent.com/73597479/121568885-d036cc00-ca3d-11eb-97e6-4643076d1cfd.png)

**Comment by khalifapro** [comment]
Fixed and confirmed https://jira.linuxfoundation.org/browse/SSB-68

**Comment by niruautomation** [comment]
Verified in JIRA
