### ISSUE TITLE
SSB-68: NPM - runtime error displayed when generating SPDX file for yarn project

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#77]
Original Reporter: nvelagapudi
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-68

spdx-sbom-generator tool version v0.0.3Clone https://github.com/gothinkster/node-express-realworld-example-appExecute yarn install. During this step observed below messagenode_modules folder is created with dependenciesruntime error displayed when generating SPDX file for yarn project when trying to generate SPDX fileNOTE I tried with other yarn project and it worked finehttps://github.com/boltpkg/bolt

**Comment by niruautomation** [comment]
Verified and closed in JIRA and hence closing the ticket
