### ISSUE TITLE
SSB-66: NPM - NOASSERTION is displayed for PackageCopyrightText when there are multiple license

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#80]
Original Reporter: nvelagapudi
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-66

spdx-sbom-generator tool version v0.0.3Test Repos that I used for testinghttps://github.com/node-red/node-redObserved that NOASSERTION is displayed for PackageCopyrightText when there are multiple licenseIn the below example both the license files have Copyright text but still the text is not displayedSPDX file (PFA file for reference)License file in package.json

**Comment by niruautomation** [comment]
Verified and closed in JIRA and hence closing the ticket
