### ISSUE TITLE
SSB-60: NPM - PackageLicenseConcluded/Declared - NOASSERTION is displayed for root package even when license exists in package.json

### ISSUE THREAD

**Issue by rynofinn** [spdx/spdx-sbom-generator#86]
Original Reporter: nvelagapudi
Environment: Not Specified
Version: Not Specified
Migrated From: http://jira.linuxfoundation.org/browse/SSB-60

spdx-sbom-generator tool version v0.0.3Test Repos that I used for testinghttps://github.com/node-red/node-redObserved that NOASSERTION is displayed for PackageLicenseConcluded/PackageLicenseDeclared even when license for root package is available in package.jsonSPDX file (PFA file for reference)Package.json (PFA file for reference) **

**Comment by niruautomation** [comment]
Verified and closed in JIRA and hence closing the ticket
